[package]
name = "backtracking"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
common.workspace = true
console.workspace = true
thiserror.workspace = true
utf8_reader.workspace = true
